/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class interpolator_Interpolate */

#ifndef _Included_interpolator_Interpolate
#define _Included_interpolator_Interpolate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     interpolator_Interpolate
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_interpolator_Interpolate_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
