/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class interpolator_Interpolate */

#ifndef _Included_interpolator_Interpolate
#define _Included_interpolator_Interpolate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     interpolator_Interpolate
 * Method:    interpolate
 * Signature: ([IIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_interpolator_Interpolate_interpolate
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
